theme: jekyll-theme-dinky
title: DeS SL1 Guidelines
description: A comprehensive and community-supported repository on how the Demon's Souls Discord server manages SL1 runs and their numerous challenge variations.
